### ISSUE TITLE
Crash with Kotlin version 1.3.70

### ISSUE THREAD

**Issue by nuhkoca** [Kotlin/kotlinx.serialization#736]
**Describe the bug**

I was able to work well with Kotlin version 1.3.61 but now I am getting crash with Kotlin version 1.3.70

`Caused by: java.lang.NoSuchMethodError: No direct method <init>(Ljava/lang/String;Lkotlinx/serialization/internal/GeneratedSerializer;I)V in class Lkotlinx/serialization/internal/SerialClassDescImpl; or its super classes (declaration of 'kotlinx.serialization.internal.SerialClassDescImpl' appears in /path)`

**To Reproduce**
Create these classes:

```
@Serializable
data class PolygonResponse(
    val maxSpeed: Int?,
    val polygons: List<Polygons?>
)
```
```
@Serializable
data class Polygons(
    val baseCapacity: Int?,
    val distanceToPolygon: Int?,
    val polygon: List<Polygon?>
)
```
```
@Serializable(with = PolygonSerializer::class)
data class Polygon(
    val coordinates: List<Double>
)
internal object PolygonSerializer : KSerializer<Polygon> {

    private val serializer = ArrayListSerializer(Double.serializer())

    override val descriptor: SerialDescriptor = StringDescriptor.withName("Polygon")

    override fun serialize(encoder: Encoder, obj: Polygon) {
        encoder.encode(serializer, obj.coordinates)
    }

    override fun deserialize(decoder: Decoder): Polygon {
        return Polygon(decoder.decode(serializer))
    }
}
```

**Expected behavior**
Serialization should work properly.

**Environment**
 - Kotlin version: [1.3.70]
 - Library version: [0.14.0]
 - Kotlin platforms: [JVM]
 - Gradle version: [6.2.1]

**Comment by PaulWoitaschek** [comment]
It's completely broken.
To verify just bump this:
https://github.com/Kotlin/kotlinx.serialization/blob/master/integration-test/gradle.properties#L5
to .70 and 23 out of 25 test fail.

**Comment by nuhkoca** [comment]
Thanks @PaulWoitaschek for the information.

**Comment by qwwdfsad** [comment]
`kotlinx-serialization` depends heavily on the compiler version (on the plugin, bundled into compiler, actually), 0.14.0 is not compatible with 1.3.70.
We will release 0.20.0 today and think out how to improve diagnostics here

**Comment by martinbonnin** [comment]
@qwwdfsad could you add some checks in the `koltinx-serialization` plugin ? Ideally detect incompatible versions and fail the build ? Or at least put a warning if the kotlin version is ahead of the one that the plugin supports ?

**Comment by sandwwraith** [comment]
Version `0.20.0`, which is compatible with `1.3.70`, is now published on JCenter and will be available on Maven Central soon. Check out the release notes: https://github.com/Kotlin/kotlinx.serialization/blob/master/CHANGELOG.md#0200--2020-03-04

**Comment by nuhkoca** [comment]
Thank you.

**Comment by delacrixmorgan** [comment]
If you're still having problems, try `clean and build` your project.
It should be getting the latest `org.jetbrains.kotlinx:kotlinx-serialization-runtime:0.20.0`.

**Comment by nuhkoca** [comment]
Please note, I have just updated the plugin and I can confirm this issue has been fixed for my case. Thanks all again.

**Comment by rrva** [comment]
java.lang.NoSuchMethodError: kotlinx.serialization.json.JsonConfiguration.<init>(ZZZZZZZLjava/lang/String;ZLjava/lang/String;Lkotlinx/serialization/UpdateMode;ILkotlin/jvm/internal/DefaultConstructorMarker;)V

**Comment by lcdsmao** [comment]
Still has this problem with Kotlin version: [1.3.70], Library version: [0.20.0].
