### ISSUE TITLE
java.lang.NoSuchMethodError: kotlinx.serialization.Encoder.beginStructure(...) multiplatform, Kotlin 1.4-M2

### ISSUE THREAD

**Issue by michel-onstein** [Kotlin/kotlinx.serialization#869]
Hi,

i'm running into an issue where during runtime the above NoSuchMethod error is thrown while serializing from the JVM module. The code works on 1.3.72. The gradlew setup follows both the 1.4-M2 structure as well as the documented settings for kotlinx.serialization. The serializable class can be either in the Common module or the JVM module.

Has anyone seen a similar issue?

**Environment**
 - Kotlin version: 1.4-M2 multi-platform
 - Library version: 0.20.0
 - Kotlin platforms: JVM and Common
 - Gradle version: 6.3

**Comment by sandwwraith** [comment]
I'd suggest to use `0.20.0-1.4-M2` version of runtime library
