### ISSUE TITLE
1.1.0 Compilation error on iOS

### ISSUE THREAD

**Issue by KevinBassaDevelopment** [Kotlin/kotlinx.serialization#1428]
**Describe the bug**

Compilation of only shared common code fails on iOS after upgrade to 1.1.0.
It works on both Windows and iOS with 1.0.1.

**Environment**
 - Kotlin version: 1.4.30-RC
 - Library version: 1.1.0
 - Kotlin platforms:  Native (iOS)
 - Gradle version: 4.2.0-rc01
 - Other relevant context: iOS

```
Execution failed for task '😒hared:linkDebugFrameworkIosX64'.
> Compilation finished with errors
Unbound public symbol for public kotlinx.serialization.json/JsonDecoder.decodeNullableSerializableElement|7091057077819363828[0] public kotlinx.serialization.json/JsonDecoder.decodeNullableSerializableElement|7091057077819363828[0]
Unbound public symbol for public kotlinx.serialization.json/JsonDecoder.decodeSerializableElement|8042733237355806987[0] public kotlinx.serialization.json/JsonDecoder.decodeSerializableElement|8042733237355806987[0]
Unbound public symbol for public kotlinx.serialization.json.internal/StreamingJsonDecoder.decodeNullableSerializableElement|7091057077819363828[0] public kotlinx.serialization.json.internal/StreamingJsonDecoder.decodeNullableSerializableElement|7091057077819363828[0]
Unbound public symbol for public kotlinx.serialization.json.internal/StreamingJsonDecoder.decodeSerializableElement|8042733237355806987[0] public kotlinx.serialization.json.internal/StreamingJsonDecoder.decodeSerializableElement|8042733237355806987[0]
Unbound public symbol for public kotlinx.serialization.internal/NamedValueDecoder.decodeNullableSerializableElement|7091057077819363828[0] public kotlinx.serialization.internal/NamedValueDecoder.decodeNullableSerializableElement|7091057077819363828[0]
Unbound public symbol for public kotlinx.serialization.internal/NamedValueDecoder.decodeSerializableElement|8042733237355806987[0] public kotlinx.serialization.internal/NamedValueDecoder.decodeSerializableElement|8042733237355806987[0]

```

I also commented in #1331, but I'm not sure if the original ticket is the same problem.

**Comment by sandwwraith** [comment]
I think it is. Turns out that deleting the functions from the klib even if they were deprecated and no one used them is a backward-incompatible change, unfortunately. Looks like you need to upgrade everything to 1.1.0 and recompile

**Comment by KevinBassaDevelopment** [comment]
What do you mean with upgrade everything to 1.1.0?
We have serialization on 1.1.0 and use very little other libs. 

shared build.gradle
```
    val ktorVersion = "1.5.2"
    val coroutinesVersion = "1.4.3-native-mt"
    val serializationVersion = "1.1.0"
  val commonMain by getting {
            dependencies {
                implementation("io.ktor:ktor-client-core:$ktorVersion") // required for kotlinx-serialization
                implementation("io.ktor:ktor-client-serialization:$ktorVersion") // required for kotlinx-serialization

                implementation("org.jetbrains.kotlinx:kotlinx-serialization-core:$serializationVersion")
                implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:$coroutinesVersion")
            }
        }
```

App build.gradle

```
 val kotlinVersion = "1.4.30-RC"


    dependencies {
        classpath("com.android.tools.build:gradle:4.2.0-rc01")
        classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion")
        classpath("org.jetbrains.kotlin:kotlin-serialization:$kotlinVersion")
    }
```

**Comment by sandwwraith** [comment]
Looks like Ktor 1.5.2 depends on serialization 1.0.1. Can you try to upgrade to Ktor 1.5.3, please?

**Comment by KevinBassaDevelopment** [comment]
This fixed the issue, thanks!

**Comment by KevinBassaDevelopment** [comment]
This fixed the issue, thanks!
