### ISSUE TITLE
NoSuchMethodError: beginStructure when upgrading to 1.4-M2

### ISSUE THREAD

**Issue by rrva** [Kotlin/kotlinx.serialization#854]
When upgrading kotlin from 1.3.70 to 1.4-M2 I get runtime deserialization exceptions:

```java.lang.NoSuchMethodError: 'kotlinx.serialization.CompositeDecoder kotlinx.serialization.Decoder.beginStructure(kotlinx.serialization.SerialDescriptor)'```

kotlinx runtime version is 0.20.0

**Comment by rrva** [comment]
Works with 0.20.0-1.4-M2
